# Generated by Django 3.2.25 on 2024-03-24 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("affirmations", "0003_rename_messsage_textaffirmations_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textaffirmations",
            name="recording",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="affirmations.audiorecording",
            ),
        ),
    ]
